/* ═══════════════════════════════════════════════════════════════════════════
   Regenerates the token-alias block inside styles.css from the Obsidian sheet.

   THE CONTRACT: the remote sheet is primary, styles.css is the backup.

   That is enforced without `@layer` and without declaring `:root`. Every token
   the shell consumes is aliased once, on `.il-shell` itself, as

       --il-t-fg2: var(--fg2, #8b93b5);

   so the host's value wins whenever it exists — a CSS fallback applies only to
   an absent custom property — and the vendored copy renders the shell when it
   does not. Nothing is written to the host document, which is the part a
   layered `:root` block could not offer: layered or not, `:root { --border: … }`
   still hands every other component on the page a --border.

   Vendored defaults are resolved transitively, so a default never depends on a
   token the host might not have:

       --gradient-avatar: linear-gradient(135deg, var(--mint), var(--cyan))
     → var(--gradient-avatar, linear-gradient(135deg,
           var(--mint, #B3D335), var(--cyan, #0ea5e9)))

   The seed set is scraped from styles.css itself — every `--il-t-x` a rule
   mentions. Use a new token and the next run vendors it; stop using one and it
   disappears. No hand-maintained list, no drift.

   NOT COVERED HERE, deliberately: the shell's three geometry values
   (--il-sidebar-width, --il-mini-sidebar-width, --il-topbar-height). They are
   NOT design tokens — they are absent from colors_and_type.css, which lives in
   the theme package, and were only ever declared on :root by the host app's own
   _variables.scss. Aliasing them would make the `missing` check below throw.
   They are hand-declared in styles.css under --il-, one dash short of --il-t-,
   so the scraper's `--il-t-[\w-]+` pattern cannot pick them up. Keep it that way.

     node scripts/sync-tokens.mjs                 rewrite the block
     node scripts/sync-tokens.mjs --check         exit 1 if stale (CI)
     node scripts/sync-tokens.mjs --source=<path> read a local sheet instead

   `--source` exists for offline work and for regenerating against a checkout of
   the design system before it is published to the CDN. It is not a second
   source of truth: the default is the URL, and `--check` in CI runs without it.
   ═══════════════════════════════════════════════════════════════════════════ */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DEFAULT_SOURCE = "https://cdn.thinktalentws48.click/starterkit/colors_and_type.css";
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const TARGET = join(ROOT, "styles.css");

const sourceArg = process.argv.find((arg) => arg.startsWith("--source="));
const SOURCE = sourceArg ? sourceArg.slice("--source=".length) : DEFAULT_SOURCE;
const isRemote = /^https?:\/\//.test(SOURCE);

const START = "/* @tokens:start — generated by scripts/sync-tokens.mjs, do not edit */";
const END = "/* @tokens:end */";

/* The sheet publishes its light scheme under MUI's attribute. */
const LIGHT_SELECTOR = '[data-mui-color-scheme="light"]';
const ALIAS = "--il-t-";
/* TWO scopes, not one, and `:is()` so the emitted block stays a single rule at
   single-class specificity.

   .il-shell covers everything inside the dashboard shell. .il-brand exists
   because AuthLogo renders on the login page, which is OUTSIDE the shell — a
   brand mark scoped only to .il-shell would resolve none of these aliases
   there, fall through to the bare host token, and render unstyled for any
   consumer that has not loaded the design system. That is precisely the
   standalone case the vendored defaults exist to cover.

   This is also why the brand components paint through classes rather than the
   inline `style={{ background: "var(--gradient-secondary)" }}` the source used:
   an inline var() reads the HOST token directly and never sees the alias, so it
   silently has no fallback at all. */
const SCOPE = ":is(.il-shell, .il-brand)";

/** Body of the first top-level `selector { … }`, by brace matching. */
function ruleBody(css, selector) {
  const at = css.indexOf(selector + " {");
  if (at === -1) throw new Error(`selector not found in token sheet: ${selector}`);
  const open = css.indexOf("{", at);
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(open + 1, i);
  }
  throw new Error(`unterminated rule: ${selector}`);
}

/** Custom properties only, in source order. Comments and `color-scheme:` dropped. */
function customProps(body) {
  const out = new Map();
  let depth = 0;
  let buf = "";
  const flush = () => {
    const decl = buf.replace(/\/\*[\s\S]*?\*\//g, "").trim();
    buf = "";
    const split = decl.indexOf(":");
    if (split === -1) return;
    const name = decl.slice(0, split).trim();
    if (name.startsWith("--")) out.set(name, decl.slice(split + 1).trim().replace(/\s+/g, " "));
  };
  for (const ch of body) {
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (ch === ";" && depth === 0) flush();
    else buf += ch;
  }
  flush();
  return out;
}

/**
 * Inline a vendored default for every var() inside a vendored value, so the
 * default stands on its own. `seen` breaks a cycle in the source sheet rather
 * than recursing forever.
 */
function selfContained(value, lookup, seen = new Set()) {
  return value.replace(/var\(\s*(--[\w-]+)\s*\)/g, (whole, name) => {
    if (seen.has(name)) return whole;
    const inner = lookup(name);
    if (inner === undefined) return whole;
    return `var(${name}, ${selfContained(inner, lookup, new Set([...seen, name]))})`;
  });
}

const sheet = isRemote
  ? await fetch(SOURCE).then((res) => {
      if (!res.ok) throw new Error(`${SOURCE} → HTTP ${res.status}`);
      return res.text();
    })
  : readFileSync(SOURCE, "utf8");

const dark = customProps(ruleBody(sheet, ":root"));
const light = customProps(ruleBody(sheet, LIGHT_SELECTOR));

const current = readFileSync(TARGET, "utf8");
const head = current.indexOf(START);
const tail = current.indexOf(END);
if (head === -1 || tail === -1) throw new Error("token markers missing from styles.css");

/* Seeds from the hand-written CSS only — the generated block is cut out first so
   an alias cannot keep itself alive by being referenced by its own siblings.

   Comments are then stripped, and that is not cosmetic. This file's own header
   explains the contract using `--il-t-fg2: var(--fg2, …)` as the worked example,
   and without this the scraper reads that prose as usage and vendors a token no
   rule applies. Caught the first time this script ran, against a stylesheet with
   no rules in it at all: one alias, sourced entirely from a comment.

   It also settles a disagreement. The consuming app's own gate
   (scripts/check-package-tokens.mjs) already strips comments before deciding
   what a package consumes — "a token merely *named* in prose does not [count]".
   Scraping comments here meant the two halves of one contract disagreed about
   what the word "consumed" means, and the package's half was the loose one. */
const handWritten = (current.slice(0, head) + current.slice(tail + END.length)).replace(
  /\/\*[\s\S]*?\*\//g,
  " ",
);
const used = new Set(
  [...new Set(handWritten.match(new RegExp(String.raw`${ALIAS}[\w-]+`, "g")) ?? [])].map(
    (alias) => "--" + alias.slice(ALIAS.length),
  ),
);

const missing = [...used].filter((name) => !dark.has(name));
if (missing.length) throw new Error(`consumed but absent from the token sheet: ${missing.join(", ")}`);

/* Emit in the sheet's own order — it groups by role (palette, text, borders,
   radii, channels), which reads better than alphabetical and is just as stable. */
const seeds = [...dark.keys()].filter((name) => used.has(name));

const darkOf = (name) => dark.get(name);
const lightOf = (name) => light.get(name) ?? dark.get(name);

const declare = (name, lookup, indent) =>
  `${indent}${ALIAS}${name.slice(2)}: var(${name}, ${selfContained(lookup(name), lookup)});`;

const darkBlock = seeds.map((name) => declare(name, darkOf, "  ")).join("\n");

/* A token earns a light declaration when its vendored default actually differs
   there — either it is redefined, or something it references is. */
const flipped = seeds.filter((name) => declare(name, darkOf, "") !== declare(name, lightOf, ""));

const lightBlock = (indent) => flipped.map((name) => declare(name, lightOf, indent)).join("\n");

const block = `${START}
/* Source: ${DEFAULT_SOURCE} — regenerate with \`pnpm sync:tokens\`.
   Each alias is \`var(<host token>, <vendored default>)\`: the host's sheet wins
   whenever it defines the token, these values render the shell when it does
   not. Scoped to ${SCOPE} — this file declares nothing on :root. */

${SCOPE} {
${darkBlock}
}

/* Light scheme. Brand hues darken on a light surface, so the channels flip with
   them: a nav-link accent drawn in the dark-surface mint lands near 1.7:1 on white. */
${LIGHT_SELECTOR} ${SCOPE},
[data-theme="light"] ${SCOPE} {
${lightBlock("  ")}
}

/* Same defaults for a host that ships no scheme attribute at all. Scoped to a
   root carrying neither: without that guard, a host running dark mode on a
   light-preference machine would pick these up. */
@media (prefers-color-scheme: light) {
  :root:not([data-mui-color-scheme]):not([data-theme]) ${SCOPE} {
${lightBlock("    ")}
  }
}
${END}`;

const next = current.slice(0, head) + block + current.slice(tail + END.length);

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error("styles.css tokens are stale — run `pnpm sync:tokens`");
    process.exit(1);
  }
  console.log(`tokens up to date (${seeds.length} aliased, ${flipped.length} flip in light)`);
} else {
  writeFileSync(TARGET, next);
  console.log(`synced ${seeds.length} tokens from ${SOURCE} (${flipped.length} flip in light)`);
}
